### ISSUE TITLE
Implement ExportPrivKeyArmor method

### ISSUE THREAD

**Issue by thomasmodeneis** [ComposableFi/relayer#6]

**Comment by jtieri** [comment]
We were considering dropping this function from the `KeyProvider` interface as we don't have any complete user story for why this is a necessary piece of functionality. If you guys see no use in such a feature we could effectively remove it.

**Comment by Kaktus-green** [comment]
@vjdmhd do you this is needed, related to the comment we got from @jtieri ?

**Comment by TxCorpi0x** [comment]
@jtieri This is related to legacy amino codec in the Cosmos-SDK, Yes? If it is we do not need it too

**Comment by jtieri** [comment]
> @jtieri This is related to legacy amino codec in the Cosmos-SDK, Yes? If it is we do not need it too

This function was used to export an encrypted copy of a private key and it existed in the relayer before my time working on it. We have no specified use cases around this or any user stories for why this would be a necessary feature though so if you guys also don't see any use in it we can likely just take this out of the `KeyProvider` interface.

**Comment by TxCorpi0x** [comment]
We do not need to export private key.
